name: Build and Release

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: nhartland/love-build@v1
        id: love-build
        with:
          app_name: "masked_king"
          love_version: "11.5"
      - uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: ${{ steps.love-build.outputs.macos-filename }}
      - uses: actions/upload-artifact@v4
        with:
          name: win32-build
          path: ${{ steps.love-build.outputs.win32-filename }}
      - uses: actions/upload-artifact@v4
        with:
          name: win64-build
          path: ${{ steps.love-build.outputs.win64-filename }}
      - uses: actions/upload-artifact@v4
        with:
          name: love-build
          path: ${{ steps.love-build.outputs.love-filename }}
      - uses: actions/upload-artifact@v4
        with:
          name: linux_x86_64-build
          path: ${{ steps.love-build.outputs.linux_x86_64-filename }}
      # create gh release only on tag pushes
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ steps.love-build.outputs.macos-filename }}
            ${{ steps.love-build.outputs.win32-filename }}
            ${{ steps.love-build.outputs.win64-filename }}
            ${{ steps.love-build.outputs.love-filename }}
            ${{ steps.love-build.outputs.linux_x86_64-filename }}
          draft: false
          prerelease: false
